// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Hash from "./Hash";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_types from "rescript/lib/es6/js_types.js";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Js_option from "rescript/lib/es6/js_option.js";

function updateNodeProps(prim0, prim1, prim2, prim3) {
  Hash.updateNodeProps(prim0, prim1, prim2, prim3);
}

function finalize(n) {
  return n & 2147483647;
}

function mixNumber(seed, n) {
  return Math.imul(seed ^ n, 16777619);
}

function hashString(seed, s) {
  var r = seed;
  for(var i = 0 ,i_finish = s.length; i <= i_finish; ++i){
    r = mixNumber(r, s.charCodeAt(i) | 0);
  }
  return r;
}

function hashNode(kind, props, children) {
  var r = hashString(-2128831035, kind);
  var k = Js_dict.get(props, "key");
  var r2 = k !== undefined && Js_types.test(k, /* String */4) ? hashString(r, k) : hashString(r, Js_option.getExn(JSON.stringify(props)));
  return Belt_List.reduceU(children, r2, mixNumber) & 2147483647;
}

function hashMemoInputs(props, children) {
  var r = Js_types.test(props.memoKey, /* String */4) ? hashString(-2128831035, props.memoKey) : hashString(-2128831035, Js_option.getExn(JSON.stringify(props)));
  return Belt_List.reduceU(children, r, mixNumber) & 2147483647;
}

export {
  updateNodeProps ,
  finalize ,
  mixNumber ,
  hashString ,
  hashNode ,
  hashMemoInputs ,
}
/* ./Hash Not a pure module */
