// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_types from "rescript/lib/es6/js_types.js";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as HashUtils from "./HashUtils.bs.js";

var symbol = "__ELEM_NODE__";

function create(kind, props, children) {
  var childrenList = Belt_List.fromArray(children);
  return {
          symbol: symbol,
          hash: HashUtils.hashNode(kind, props, Belt_List.map(childrenList, (function (n) {
                      return HashUtils.mixNumber(n.hash, n.outputChannel);
                    }))),
          kind: kind,
          props: props,
          outputChannel: 0,
          children: childrenList
        };
}

function isNode(a) {
  var match = Js_types.classify(a);
  if (typeof match === "number") {
    return false;
  }
  if (match.TAG !== /* JSObject */3) {
    return false;
  }
  var s = Js_types.classify(a.symbol);
  if (typeof s === "number" || s.TAG !== /* JSString */1) {
    return false;
  } else {
    return s._0 === symbol;
  }
}

function shallowCopy(node) {
  return {
          symbol: node.symbol,
          hash: node.hash,
          kind: node.kind,
          props: Object.assign({}, node.props),
          outputChannel: node.outputChannel,
          generation: {
            contents: 0
          }
        };
}

export {
  symbol ,
  create ,
  isNode ,
  shallowCopy ,
}
/* HashUtils Not a pure module */
