#pragma once

#include <initializer_list>
#include <optional>
#include <type_traits>
#include <utility>
#include <vector>

#include "../Value.h"

namespace elem::lib {
    // Wraps a field type to make it mandatory in a DEFINE_PROPS_STRUCT: omitting
    // it from aggregate init falls back to value-init, which is ill-formed here
    // because the default constructor is deleted.
    template <typename T>
    struct Required {
        T value;
        Required() = delete;
        Required(T v) : value(std::move(v)) {}

        // Lets container-typed fields (e.g. Required<js::Array> or
        // Required<std::vector<SparSeqStep>>) be brace-initialized directly, e.g.
        // `.seq = {1.0, 2.0, 3.0}` or `.seq = {{.value=1.0, .tickTime=0.0}}`, instead of
        // needing `.seq = {{1.0, 2.0, 3.0}}` / naming the element type explicitly.
        //
        // The element type is pinned to T::value_type (via the defaulted T2 param) rather
        // than deduced from the call, because a brace-elided nested-struct element like
        // `{.value=1.0, .tickTime=0.0}` has no type of its own to deduce from -- it can only
        // aggregate-initialize against a concrete target type, which T::value_type provides.
        template <typename T2 = T, typename = std::enable_if_t<
            std::is_constructible_v<T2, std::initializer_list<typename T2::value_type>>>>
        Required(std::initializer_list<typename T2::value_type> il) : value(il) {}

        operator T&() { return value; }
        operator const T&() const { return value; }
    };

    namespace detail {
        template <typename T>
        struct is_optional : std::false_type {};
        template <typename T>
        struct is_optional<std::optional<T>> : std::true_type {};

        template <typename T>
        struct is_required : std::false_type {};
        template <typename T>
        struct is_required<Required<T>> : std::true_type {};

        // Detects Props structs generated by DEFINE_PROPS_STRUCT (or anything else
        // exposing a takeJsObject() member), so they can be nested inside other
        // Props structs and converted automatically.
        template <typename T, typename = void>
        struct has_take_js_object : std::false_type {};
        template <typename T>
        struct has_take_js_object<T, std::void_t<decltype(std::declval<T&>().takeJsObject())>> : std::true_type {};

        // True only for std::vector<T> where T itself is a nested Props struct. Defined as
        // its own trait (rather than `is_vector<T> && has_take_js_object<T::value_type>`)
        // because `&&` in an `if constexpr` condition still requires both operands to be
        // well-formed, and `T::value_type` doesn't exist for non-vector T.
        template <typename T>
        struct is_vector_of_props : std::false_type {};
        template <typename T>
        struct is_vector_of_props<std::vector<T>> : has_take_js_object<T> {};

        // Converts a field value into whatever insertPropField should hand to js::Object:
        // a nested Props struct becomes its own takeJsObject() result, a vector of nested
        // Props structs becomes a js::Array of those results, and everything else passes through.
        template <typename T>
        auto toJsValue(T&& value) {
            using Decayed = std::decay_t<T>;
            if constexpr (has_take_js_object<Decayed>::value) {
                return value.takeJsObject();
            } else if constexpr (is_vector_of_props<Decayed>::value) {
                js::Array arr;
                arr.reserve(value.size());
                for (auto& item : value) {
                    arr.push_back(item.takeJsObject());
                }
                return arr;
            } else {
                return std::forward<T>(value);
            }
        }

        template <typename T>
        void insertPropField(js::Object& obj, const char* name, T&& value) {
            using Decayed = std::decay_t<T>;
            if constexpr (is_optional<Decayed>::value) {
                if (value.has_value()) {
                    obj.insert({name, toJsValue(*std::forward<T>(value))});
                }
            } else if constexpr (is_required<Decayed>::value) {
                obj.insert({name, toJsValue(std::move(value.value))});
            } else {
                obj.insert({name, toJsValue(std::forward<T>(value))});
            }
        }
    }

    #define ELEM_DECLARE_FIELD(name, type) type name;
    #define ELEM_INSERT_FIELD(name, type) elem::lib::detail::insertPropField(jsProps, #name, std::move(name));

    // Counts total variadic args (2 per field)
    #define ELEM_ARG_COUNT(...) ELEM_ARG_COUNT_IMPL(__VA_ARGS__, \
        20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0)
    #define ELEM_ARG_COUNT_IMPL(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,N,...) N

    #define ELEM_CONCAT_(a, b) a##b
    #define ELEM_CONCAT(a, b) ELEM_CONCAT_(a, b)

    #define ELEM_FOR_EACH_PAIR_2(action, name, type)  action(name, type)
    #define ELEM_FOR_EACH_PAIR_4(action, name, type, ...)  action(name, type) ELEM_FOR_EACH_PAIR_2(action, __VA_ARGS__)
    #define ELEM_FOR_EACH_PAIR_6(action, name, type, ...)  action(name, type) ELEM_FOR_EACH_PAIR_4(action, __VA_ARGS__)
    #define ELEM_FOR_EACH_PAIR_8(action, name, type, ...)  action(name, type) ELEM_FOR_EACH_PAIR_6(action, __VA_ARGS__)
    #define ELEM_FOR_EACH_PAIR_10(action, name, type, ...) action(name, type) ELEM_FOR_EACH_PAIR_8(action, __VA_ARGS__)
    #define ELEM_FOR_EACH_PAIR_12(action, name, type, ...) action(name, type) ELEM_FOR_EACH_PAIR_10(action, __VA_ARGS__)
    #define ELEM_FOR_EACH_PAIR_14(action, name, type, ...) action(name, type) ELEM_FOR_EACH_PAIR_12(action, __VA_ARGS__)
    // Extend with _16, _18, ... if a Props struct ever needs more fields than this.

    #define ELEM_FOR_EACH_PAIR(action, ...) \
        ELEM_CONCAT(ELEM_FOR_EACH_PAIR_, ELEM_ARG_COUNT(__VA_ARGS__))(action, __VA_ARGS__)

    // Declares a struct with the given name/type pairs plus a takeJsObject() method
    // that moves each field into a js::Object, skipping unset std::optional fields.
    // takeJsObject() consumes the struct's fields, so it can only be called once.
    #define DEFINE_PROPS_STRUCT(StructName, ...)                    \
        struct StructName {                                        \
            ELEM_FOR_EACH_PAIR(ELEM_DECLARE_FIELD, __VA_ARGS__)     \
            js::Object takeJsObject() {                            \
                js::Object jsProps;                                 \
                ELEM_FOR_EACH_PAIR(ELEM_INSERT_FIELD, __VA_ARGS__)  \
                return jsProps;                                     \
            }                                                       \
        };
}
