// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Hash from "./Hash";

function hashNumber(prim0, prim1) {
  return Hash.hashNumber(prim0, prim1);
}

function hashString(prim0, prim1) {
  return Hash.hashString(prim0, prim1);
}

function hashNode(prim0, prim1, prim2) {
  return Hash.hashNode(prim0, prim1, prim2);
}

function hashMemoInputs(prim0, prim1) {
  return Hash.hashMemoInputs(prim0, prim1);
}

function hashToHexId(prim) {
  return Hash.hashToHexId(prim);
}

function hexIdToHash(prim) {
  return Hash.hexIdToHash(prim);
}

function updateNodeProps(prim0, prim1, prim2, prim3) {
  Hash.updateNodeProps(prim0, prim1, prim2, prim3);
}

export {
  hashNumber ,
  hashString ,
  hashNode ,
  hashMemoInputs ,
  hashToHexId ,
  hexIdToHash ,
  updateNodeProps ,
}
/* ./Hash Not a pure module */
